name: CI
on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

env:
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 20971520

jobs:
  lib:
    name: Test ATE Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run Tests
      run: |
        cd lib
        cargo test

  wasmer-dfs:
    name: Test Wasmer Distributed FileSystem
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Fuse
      run: |
        sudo apt-get install fuse libfuse-dev libfuse3-dev
    - name: First the Unit Tests
      run: |
        cd wasmer-dfs
        cargo test

  wasmer-term:
    name: Build Wasmer/Wasmer Terminal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: |
        cd wasmer-web
        npm install
        npm run build

  atenet:
    name: Test ATE Mesh Networking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run Tests
      run: |
        cd atenet
        cargo test
